# Generated by Django 5.1.7 on 2025-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='timestamp',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='location',
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Untitled Submission', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
