# Generated by Django 5.1.7 on 2025-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_timestamp_submission_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Historic Places', 'Historic Places'), ('Markets', 'Markets'), ('Cafés', 'Cafés'), ('Nature Spots', 'Nature Spots'), ('Events', 'Events')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='submissions/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
