# Generated by Django 5.1.5 on 2025-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_event_usersubmission_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('blog_type', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Business', 'Business'), ('Fitness', 'Fitness'), ('Fashion', 'Fashion'), ('Finance', 'Finance')], max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='usersubmission',
            old_name='title',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Defualt Event Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
